kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-resource-config
data:
  managed: |
    {"blobstorage":"aws","redis":"aws", "postgres":"aws"}
  workshop: |
    {"blobstorage":"openshift", "redis":"openshift", "postgres":"openshift"}