kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-resources-aws-strategies
data:
  blobstorage: |
    {"development": { "region": "eu-west-1", "createStrategy": {}, "deleteStrategy": {} }}
  redis: |
    {"development": { "region": "eu-west-1", "createStrategy": {}, "deleteStrategy": {} }}
  postgres: |
    {"development": { "region": "eu-west-1", "createStrategy": {}, "deleteStrategy": {} }}
  _network: |
    {"development": { "region": "eu-west-1", "createStrategy": { "CidrBlock": "10.1.0.0/16" }, "deleteStrategy": {} }}
    
