kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-resource-config
  namespace: kube-system
data:
  managed: |
    {"blobstorage":"aws", "smtpcredentials": "aws"}
  workshop: |
    {"blobstorage":"openshift", "smtpcredentials": "openshift"}
