apiVersion: integreatly.org/v1alpha1
kind: Postgres
metadata:
  # name must be between 1-40 characters
  name: example-postgres
spec:
  # i want my postgres storage information output in a secret named example-postgres-sec
  secretRef:
    name: example-postgres-sec
  # i want a postgres storage of a development-level tier
  tier: development
  # i want a postgres storage for the type workshop
  type: workshop
