apiVersion: integreatly.org/v1alpha1
kind: Postgres
metadata:
  # name must be between 1-40 characters
  name: example-postgres
spec:
  # i want my postgres storage information output in a Secret named test in the Namespace cloud-resource-operator
  secretRef:
    name: example-postgres
    namespace: cloud-resource-operator
  # i want a postgres storage of a development-level tier
  tier: development
  # i want a postgres storage for the type managed
  type: workshop
