apiVersion: integreatly.org/v1alpha1
kind: BlobStorage
metadata:
  # name must be between 1-40 characters
  name: example-blobstorage
spec:
  # i want my blob storage information output in a secret named example-blobstorage-sec
  secretRef:
    name: example-blobstorage-sec
  # i want a blob storage of a development-level tier
  tier: development
  # the type i want for a blob storage
  type: REPLACE_ME
