apiVersion: integreatly.org/v1alpha1
kind: SMTPCredentialSet
metadata:
  # name must be between 1-40 characters
  name: example-smtpcredentialset
spec:
  # i want my smtp cred information output in a Secret named example-smtpcredentialset-sec
  secretRef:
    name: example-smtpcredentialset-sec
  # i want an smtp cred set of a development-level tier
  tier: development
  # the type i want for an smpt cred
  type: REPLACE_ME